name: Build and Deploy
on:
  push:
    branches:
      - 'markdown'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout ğŸ›ï¸
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: ğŸ”§ Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
          cp slides/index.html public/index.html

      - name:  ğŸš€ Deploy ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
